name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Deploy
        run: echo Deploying to staging env

      - name: Git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Prepare auto-pr branch
        run: |
          git fetch origin main
          git checkout -b auto-pr
          git commit --allow-empty -m "chore: promote staging → main [skip ci]"
          git push origin auto-pr --force

      - name: Open Main PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_PR_TOKEN }}
          branch: auto-pr
          base: main
          title: Promote Staging to Production
          body: "PR criado automaticamente a partir de staging"
          draft: false
          delete-branch: true