name: Deploy Staging

on:
    push:
        branches:
            - staging

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy
              run: echo Deploying to staging env

            - name: Open Main PR
              uses: peter-evans/create-pull-request@v7
              with:
                token: ${{ secrets.AUTO_PR_TOKEN }}
                base: main
                branch: staging                
                commit-message: "Auto PR"
                title: Promote Staging to Production
                delete-branch: true
                allow-empty-commit: true            
            